### ISSUE TITLE
KeyError: 'depth_multiple'

### ISSUE THREAD

**Issue by SpectrePrediction** [OutBreak-hui/YoloV5-Flexible-and-Inference#1]
```python
Traceback (most recent call last):
  File "/hy-nas/yolov5/train.py", line 655, in <module>
    main(opt)
  File "/hy-nas/yolov5/train.py", line 552, in main
    train(opt.hyp, opt, device, callbacks)
  File "/hy-nas/yolov5/train.py", line 124, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/hy-nas/yolov5/models/yolo.py", line 100, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/hy-nas/yolov5/models/yolo.py", line 228, in parse_model
    anchors, nc, gd, gw = d['anchors'], d['nc'], d['depth_multiple'], d['width_multiple']
KeyError: 'depth_multiple'
```
我使用命令
```
python train.py --img 3000 --batch 4 --epochs 5 --cfg ./models/yolov5_ConvNeXt_small.yaml --data reef_f1_naive.yaml --name l6_3600_uflip_vm5_f1 --hyp data/hyps/hyp.heavy.2.yaml
```
其中yolov5_ConvNeXt_small.yaml nc被设置为1

**Comment by SpectrePrediction** [comment]
我在其中添加了这个，但是出现了新的问题
```python
depth_multiple: 0.33
width_multiple: 0.50
```
问题：
```python
Traceback (most recent call last):
  File "/hy-nas/yolov5/train.py", line 655, in <module>
    main(opt)
  File "/hy-nas/yolov5/train.py", line 552, in main
    train(opt.hyp, opt, device, callbacks)
  File "/hy-nas/yolov5/train.py", line 124, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/hy-nas/yolov5/models/yolo.py", line 110, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/hy-nas/yolov5/models/yolo.py", line 125, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "/hy-nas/yolov5/models/yolo.py", line 157, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/hy-nas/yolov5/models/common.py", line 51, in forward
    return self.act(self.bn(self.conv(x)))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [512, 768, 1, 1], expected input[1, 1024, 8, 8] to have 768 channels, but got 1024 channels instead
```
事实上我到这一步都是一头雾水，很抱歉，我没能掌握

**Comment by SpectrePrediction** [comment]
我好像找到问题所在了

**Comment by SpectrePrediction** [comment]
我只能使用small和tiny进行训练，否则报错
